In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
b = ([9,8,7],[6,5,4],[3,2,1])
b

([9, 8, 7], [6, 5, 4], [3, 2, 1])

In [3]:
b = np.array(b)

In [4]:
c = a*b
c

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [5]:
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [6]:
d = a+b
d

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [7]:
a = np.sin(a*np.pi)
a

array([[ 1.22464680e-16, -2.44929360e-16,  3.67394040e-16],
       [-4.89858720e-16,  6.12323400e-16, -7.34788079e-16],
       [ 8.57252759e-16, -9.79717439e-16,  1.10218212e-15]])

In [8]:
e = np.dot(a,b)
e

array([[ 7.34788079e-16,  4.89858720e-16,  2.44929360e-16],
       [-2.93915232e-15, -2.32682892e-15, -1.71450552e-15],
       [ 5.14351656e-15,  4.16379912e-15,  3.18408168e-15]])

In [9]:
e = np.dot(a[1], b[1])
e

-2.816687638038912e-15